### ISSUE TITLE
Simple authentication failed camunda 8 run

### ISSUE THREAD

**Issue by luqmanahmads** [camunda-community-hub/camunda-tasklist-client-java#269]
I would like to use community client with Camunda 8 Run for exploring camunda feature, but got authentication failed with simple authentication:
`java.lang.RuntimeException: Unable to authenticate due to missing Set-Cookie TASKLIST-SESSION`

But Camunda 8 auth endpoint 
http://localhost:8080/api/login?username=demo&password=demo
only Set-Cookie for 'OPERATE-SESSION' when using postman:
`OPERATE-SESSION=19ED32B439A316FAF49B7B9EAFxxxxxx; Path=/; HttpOnly; SameSite=Lax`

Source code check, it only look for 'TASKLIST-SESSION' and will throw runtime exception if it is not found.
`String sessionCookieName = "TASKLIST-SESSION";`

What did I miss? is it expected? What do you suggest to use camunda tasklist community client with camunda 8 run?
Thank you!

---

Camunda Run Version: 8.6.9
Community Client Version: 8.6.8
application.yaml:
```
tasklist:
  client:
    enabled: true
    profile: simple
    base-url: http://localhost:8080
    username: demo
    password: demo
    session-timeout: PT10M
```
